model:
  channels: 32
  num_blocks: 7
  semantic_classes: 13
  instance_classes: 11
  sem2ins_classes: [0,1]
  semantic_only: False
  semantic_weight: False
  with_coords: True
  ignore_label: -100
  voxel_scale: 50
  use_spp_pool: True
  filter_bg_thresh: 0.4
  iterative_sampling: True
  instance_head_cfg:
    dec_dim: 128
    n_sample_pa1: 2048
    n_queries: 256
    radius_scale: 1
    radius: 0.2
    neighbor: 32
  test_cfg:
    x4_split: True
    logit_thresh: 0.0
    score_thresh: 0.5
    npoint_thresh: 400
    type_nms: 'standard'
    topk: -1
    nms_threshold: 0.2

  fixed_modules: []

data:
  train:
    type: 's3dis'
    data_root: '/home/pengzhen/code/pointcloud_dataset_set/dataset/s3dis/'
    prefix: ['Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6']
    suffix: '_inst_nostuff'
    repeat: 20
    training: True
    voxel_cfg:
      scale: 40
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
  test:
    type: 's3dis'
    data_root: '/home/pengzhen/code/pointcloud_dataset_set/dataset/s3dis/'
    prefix: 'Area_5'
    suffix: '_inst_nostuff'
    training: False
    voxel_cfg:
      scale: 40
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000


dataloader:
  train:
    batch_size: 8
    num_workers: 0
  test:
    batch_size: 4
    num_workers: 0

optimizer:
  type: 'AdamW'
  lr: 0.001
  weight_decay: 0.0001

save_cfg:
  semantic: False
  offset: False
  instance: True
  offset_vertices: False
  nmc_clusters: False
  object_conditions: False

fp16: False
epochs: 100
step_epoch: 10
save_freq: 4
pretrain: '/home/pengzhen/code/instanceSeg/ISBNet/work_dirs/s3dis/isbnet_backbone_s3dis_area5/default/latest.pth' # We can load pretrain of ScanNetV2 or train from scratch
work_dir: ''

best weight: '/home/pengzhen/code/instanceSeg/ISBNet/work_dirs/s3dis/isbnet_backbone_s3dis_area5/default/latest.pth'
